### ISSUE TITLE
Installation auf Ubuntu 20.04

### ISSUE THREAD

**Issue by maxfuehringer** [etsstiffler/Etherparser#2]
Hallo!

Ich bin neu auf github und kenne mich noch nicht so gut aus :-)
Irgendwie schaut das jetzt anders aus, als letztens, wo hier noch die Linxu-Anleitung stand. Damit hatte ich etwas Probleme, Du schriebst aber im BBB-Forum, man sollte hier schreiben, also mache ich das.
Unter Ubuntu 20.04 hat es bei mir so funktioniert:

sudo apt install python3-tk python3-pip git
git clone https://github.com/etsstiffler/Etherparser
cd Etherparser
pip3 install -r requirements.txt
python3 etherparser.py

Danke für das geile Ding, jetzt fühlen sich alle in BBB deutlich sicherer, ohne die geteilten Notizen abschalten zu müssen.

LG
Max

**Comment by etsstiffler** [comment]
Hallo Max,
danke für dein Feedback. Ich habe tatsächlich nur eine Python Version auf meinem System. Nehme das ganze in die README mit auf.
